---
title: xBuddha - STAY ZEN, STAY xBuddha!
author: xBuddha team
email: support@xbuddha.co
description: xBuddha - STAY ZEN, STAY xBuddha!
baseurl: "/site"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
