title: xBuddha
author: xBuddha team
email: support@forestry.io
description: >-
  xBuddha xBuddha.
baseurl: "/site"
url: ""

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus

